---
- name: maintenance nodes audit
  hosts: all
  gather_facts: no
  serial: "{{ serial_number|default(100) }}"
  ignore_errors: true

  tasks:
    - name: Check Node Name
      shell: all
      register: dcg02_output

    - name: Check Node IP
      shell: curl --max-time 2 -sk "http://$(hostname -f):8500/v1/health/node/$(hostname -s)" | jq -r '.[] | "\(.CheckID):\(.Status)"' |grep -v pass
      register: node_ip_output

    - name: Check Ping Status
      ping:
      register: ping_output

    - name: Check SSH Status
      wait_for:
        host: "{{ ansible_host }}"
        port: 22
        timeout: 5
      register: ssh_status_output

    # Display Gathered Information

- name: Display Gathered Information
  debug:
    var: "{{ item }}"
  loop:
    - node_name_output
    - node_ip_output
    - ping_output
    - ssh_status_output
